# Generated by scripts/homebrew-formula.sh in scaleninja/drivesync. Do not edit by hand.
class Drivesync < Formula
  desc "Push, pull and diff a local directory against Google Drive"
  homepage "https://scaleninja.com/drivesync/"
  license "MIT"

  livecheck do
    url :stable
    strategy :github_latest
  end

  on_macos do
    on_arm do
      url "https://github.com/scaleninja/drivesync/releases/download/v0.4.0/dsync-macos-arm64"
      sha256 "7eff15c3af52a8a799044cba33917494334af3a45b5ae22886aacbdd5bc052b2"
    end
    on_intel do
      url "https://github.com/scaleninja/drivesync/releases/download/v0.4.0/dsync-macos-x86_64"
      sha256 "b894a5935558d8c63b62ee8597510c59d57e859a47c9a5c3f6c77f5e12bebff9"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/scaleninja/drivesync/releases/download/v0.4.0/dsync-linux-arm64"
      sha256 "614e06ae4da9c3bcaefa208ac75c2077658a6e01c7e3c49330a4dc5d29073d90"
    end
    on_intel do
      url "https://github.com/scaleninja/drivesync/releases/download/v0.4.0/dsync-linux-x86_64"
      sha256 "4a568c46df4dc8b45bda9f04bc3e5238896ad941ddf243cc06c8dedd4782f14f"
    end
  end

  def install
    os = OS.mac? ? "macos" : "linux"
    arch = Hardware::CPU.arm? ? "arm64" : "x86_64"
    bin.install "dsync-#{os}-#{arch}" => "dsync"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/dsync version")
  end
end
