# Generated by scripts/homebrew-formula.sh in scaleninja/drivesync. Do not edit by hand.
class Drivesync < Formula
  desc "Push, pull and diff a local directory against Google Drive"
  homepage "https://scaleninja.com/drivesync/"
  license "MIT"

  livecheck do
    url :stable
    strategy :github_latest
  end

  on_macos do
    on_arm do
      url "https://github.com/scaleninja/drivesync/releases/download/v0.3.0/dsync-macos-arm64"
      sha256 "0b146c41a835d66d0075ef1566832dae002a4a94f3f3594222aeaa91db165986"
    end
    on_intel do
      url "https://github.com/scaleninja/drivesync/releases/download/v0.3.0/dsync-macos-x86_64"
      sha256 "7184d0cc671519a5267f7034d87de6384fe3aa27ec54a2870b69d71765193481"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/scaleninja/drivesync/releases/download/v0.3.0/dsync-linux-arm64"
      sha256 "ce4b4a7422852dd61bf831d7a46a1c4d041f261f4edebbfe4a273d87e62ee2a7"
    end
    on_intel do
      url "https://github.com/scaleninja/drivesync/releases/download/v0.3.0/dsync-linux-x86_64"
      sha256 "dd52f2a691e4a8c484c751abce73bef1936b06b2ac025827219a3651ccbad10c"
    end
  end

  def install
    os = OS.mac? ? "macos" : "linux"
    arch = Hardware::CPU.arm? ? "arm64" : "x86_64"
    bin.install "dsync-#{os}-#{arch}" => "dsync"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/dsync version")
  end
end
