# Generated by scripts/homebrew-formula.sh in scaleninja/drivesync. Do not edit by hand.
class Drivesync < Formula
  desc "Push, pull and diff a local directory against Google Drive"
  homepage "https://scaleninja.com/drivesync/"
  license "MIT"

  livecheck do
    url :stable
    strategy :github_latest
  end

  on_macos do
    on_arm do
      url "https://github.com/scaleninja/drivesync/releases/download/v0.4.1/dsync-macos-arm64"
      sha256 "70f9ffe12045268a6bd4f26984d12f1e6487215d7ce258148d7ee9da48bb5c0b"
    end
    on_intel do
      url "https://github.com/scaleninja/drivesync/releases/download/v0.4.1/dsync-macos-x86_64"
      sha256 "99948ddcd44c3e9c5671228a68267222186dbf73255a18ad7f48326f01637bdf"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/scaleninja/drivesync/releases/download/v0.4.1/dsync-linux-arm64"
      sha256 "e2fc1159af9f40d9b58412b9c25533becb61f392ed8a60b20bb35a1fb4604c14"
    end
    on_intel do
      url "https://github.com/scaleninja/drivesync/releases/download/v0.4.1/dsync-linux-x86_64"
      sha256 "36e78f91b671b185d94eefab5a0ed086d51d101a76e31ba9471ae911c43b28a0"
    end
  end

  def install
    os = OS.mac? ? "macos" : "linux"
    arch = Hardware::CPU.arm? ? "arm64" : "x86_64"
    bin.install "dsync-#{os}-#{arch}" => "dsync"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/dsync version")
  end
end
